sudo: false

notifications:
  email:
    - renato.mendes.1123@gmail.com

branches:
  only:
    - 0.0.1

install: true 
  
before_deploy:
  - curl -LO https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
  - unzip terraform_0.11.3_linux_amd64.zip
  - chmod +x ./terraform
  - sudo mv ./terraform /usr/local/bin/terraform
  - terraform
  - ls -l
  
deploy:
  - provider: script
    script:
      - ls -l
    on:
      branch: 
        - "0.0.1"
  
